# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-28 00:07
from __future__ import unicode_literals

from django.db import migrations
import mezzanine.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='background',
            field=mezzanine.core.fields.FileField(blank=True, max_length=255, verbose_name='Background'),
        ),
    ]
