# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-28 05:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0002_auto_20170428_0107'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='subtitle',
            field=models.CharField(blank=True, help_text='The subheading over the background', max_length=200, null=True, verbose_name='Subtitle'),
        ),
    ]
