# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-28 17:12
from __future__ import unicode_literals

from django.db import migrations
import mezzanine.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_auto_20150527_1555'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='background',
            field=mezzanine.core.fields.FileField(blank=True, max_length=255, verbose_name='Background'),
        ),
    ]
