# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-29 09:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_page_subtitle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='subtitle',
        ),
        migrations.AddField(
            model_name='page',
            name='heading',
            field=models.CharField(blank=True, help_text='The heading over the background', max_length=200, null=True, verbose_name='Heading'),
        ),
        migrations.AddField(
            model_name='page',
            name='subheading',
            field=models.CharField(help_text='The subheading over the background', max_length=200, null=True, verbose_name='Subheading'),
        ),
    ]
