# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-29 17:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_auto_20170429_1002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='heading',
            field=models.CharField(blank=True, help_text='The heading over the background. Title is used if left blank', max_length=200, null=True, verbose_name='Heading'),
        ),
    ]
