# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-29 03:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20150527_1555'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='subtitle',
            field=models.CharField(help_text='The subtitle over the background', max_length=200, null=True, verbose_name='Subtitle'),
        ),
    ]
