---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: mezzanine
  namespace: lukeaddison
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: mezzanine
    spec:
      containers:
      - name: mezzanine
        image: dippynark/lukeaddison.co.uk
        ports:
        - containerPort: 8000
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 3
        readinessProbe:
          httpGet:
            path: /
            port: 8000
          periodSeconds: 3
        volumeMounts:
        - name: local-settings
          mountPath: /usr/src/app/lukeaddison_co_uk/local
        - name: static-storage
          mountPath: /usr/src/app/static
      volumes:
      - name: local-settings
        secret:
          secretName: local-settings  
      - name: static-storage
        persistentVolumeClaim:
          claimName: static   
---
apiVersion: v1
kind: Service
metadata:
  name: mezzanine
  namespace: lukeaddison
spec:
  selector:
    app: mezzanine
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: memcached
  namespace: lukeaddison
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: memcached
    spec:
      containers:
      - name: memcached
        image: memcached:1.4
        ports:
        - containerPort: 11211
          protocol: TCP
        livenessProbe:
          tcpSocket:
            port: 11211
          initialDelaySeconds: 30
          periodSeconds: 3
        readinessProbe:
          tcpSocket:
            port: 11211
          periodSeconds: 3
---
apiVersion: v1
kind: Service
metadata:
  name: memcached
  namespace: lukeaddison
spec:
  selector:
    app: memcached
  ports:
  - protocol: TCP
    port: 11211
    targetPort: 11211


