---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: postgres
  namespace: lukeaddison
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: postgres
    spec:   
      containers:
      - name: postgres
        image: postgres:9.3           
        env:
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name:  postgres
              key: username
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name:  postgres
              key: password
        - name: POSTGRES_DB
          value: "lukeaddison_co_uk"
        - name: PGDATA
          value: "/var/lib/postgresql/data/pgdata"
        resources:
          requests:
            memory: 512Mi
            cpu: 500m
          limits:            
            memory: 1Gi
            cpu: 1000m
        livenessProbe:
          exec:
            command:
            - pg_isready
            - -h
            - localhost
            - -U
            - postgres
          initialDelaySeconds: 180
          timeoutSeconds: 5
        readinessProbe:
          exec:
            command:
            - pg_isready
            - -h
            - localhost
            - -U
            - postgres
          initialDelaySeconds: 5
          timeoutSeconds: 1
        ports:
        - containerPort: 5432
          name: postgres
        volumeMounts:
        - name: postgres-persistent-storage
          mountPath: "/var/lib/postgresql/data"   
#      nodeSelector:
#        kubernetes.io/hostname: node1.lukeaddison.co.uk
      volumes:
      - name: postgres-persistent-storage
        persistentVolumeClaim:
          claimName: postgres
#        hostPath:
#          path: /lukeaddison.co.uk/postgres
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: lukeaddison
spec:
  ports:
  - port: 5432
  selector:
    app: postgres
    
        
