# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-27 23:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import mezzanine.core.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pages', '0003_auto_20150527_1555'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pages.Page')),
                ('content', mezzanine.core.fields.RichTextField(verbose_name='Content')),
                ('heading', models.CharField(help_text='The heading over the background', max_length=200)),
                ('subheading', models.CharField(help_text='The subheading over the background', max_length=200)),
                ('background', mezzanine.core.fields.FileField(blank=True, max_length=2000, null=True, verbose_name='Background')),
            ],
            options={
                'verbose_name': 'Home page',
                'verbose_name_plural': 'Home pages',
                'ordering': ('_order',),
            },
            bases=('pages.page', models.Model),
        ),
    ]
