# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-30 15:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_auto_20170430_1637'),
        ('theme', '0003_auto_20170428_1906'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='page_ptr',
        ),
        migrations.DeleteModel(
            name='HomePage',
        ),
    ]
